### ISSUE TITLE
How to import the library in build.gradle file

### ISSUE THREAD

**Issue by Ankit0080** [HeyAlex/BottomDrawer#12]
Please provide Java Implementation

**Comment by Ankit0080** [comment]
This is what i have done so far

public class MyProfileFragment extends BottomDrawerFragment {

    public MyProfileActivity activity;


    @Override
    public void onAttach(@NonNull Activity activity) {
        super.onAttach(activity);
        this.activity=(MyProfileActivity) activity;
    }

    @Override
    public BottomDrawerDialog configureBottomDrawer() {
        BottomDrawerDialog.Builder builder = new BottomDrawerDialog.Builder(activity);
        builder.setTheme(R.style.bottomDrawer);
        builder.setCancelableOnTouchOutside(false);
       // bottomDrawerDialog.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);
        return builder.build();

    }


Please tell me where do i need to add OnSlide method i am using java code because slide not working

**Comment by HeyAlex** [comment]
@Ankit0080  For what purpose do you need onSlide method? In your implementation i don't see a onCreateView method with inflating a view.

**Comment by Ankit0080** [comment]
I have already implemented oncreateView but using this piece of code there is no bottom sheet build , apart from it the addBottomsheetCallback is not working using Java Can you provide any working sample in Java using this package.?

**Comment by HeyAlex** [comment]
@Ankit0080 take a look at sample [here](https://github.com/HeyAlex/BottomDrawer/blob/b308a29c0eadda15cf29c335f19157b9fd84be48/app/src/main/java/com/github/heyalex/bottomdrawerexample/GoogleTaskJavaSampleDialog.java). You can check out develop branch to check how it works.

**Comment by HeyAlex** [comment]
@Ankit0080  feel free to reopen
