### ISSUE TITLE
it seems can't fetch from jitPack

### ISSUE THREAD

**Issue by AlphaGao1993** [HeyAlex/BottomDrawer#3]
![image](https://user-images.githubusercontent.com/18735052/66794224-3f8bae00-ef33-11e9-8e9e-f1c9d69755ce.png)

**Comment by HeyAlex** [comment]
@AlphaGao1993 it wasn't ready when you reached this library. Right now you can add library through jitpack's maven:

`implementation 'com.github.HeyAlex:BottomDrawer:v1.0.0'`
