### ISSUE TITLE
No support for navigation in bottom sheet

### ISSUE THREAD

**Issue by hassan31** [HeyAlex/BottomDrawer#6]
Hi, first of all, it was really great to have this control. I like it very much.
Secondly, I'm wondering if I could have the feature of navigating multiple fragments within bottom sheet.

Example: I opened the bottom sheet, and within that sheet I want to add another fragment or replace one more fragment and so on. Is this possible? If so, currently how can I add another fragment within same bottom sheet. I'm new in Android and trying to implement same as iOS.

Look forward to hearing from you.

Regards,
Hassan

**Comment by HeyAlex** [comment]
Hi @hassan31 , there are 2 options that can helps you:  
1. Use _ChildFragmentManager_ in BottomSheetFragment
2. You can make your own view like bottom sheet provided by this library. Just check https://medium.com/@heyalex/bottom-sheet-like-in-a-google-task-app-16cca3766204?source=friends_link&sk=578bb8863b4b7e2aaa7f3cfa351762cf. Right now this library supports only behavior like Modal Bottom Sheet
