### ISSUE TITLE
Java Usage?

### ISSUE THREAD

**Issue by omkar-tenkale** [HeyAlex/BottomDrawer#8]
How to use the library in java

I couldn't go further 

```
public class BottomDrawerFragment extends com.github.heyalex.bottomdrawer.BottomDrawerFragment {

}
```

Neither it asks to overrride any methods

**Comment by HeyAlex** [comment]
Sorry for that late reply. 

I can confirm that code snippet above will work in java.

`public class BottomDrawerFragment extends com.github.heyalex.bottomdrawer.BottomDrawerFragment {
    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater,
                             @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.your_cool_layout, container, false);
        return view;
    }
}`

But yes, this library is Kotlin first, i will take a look at java API.

**Comment by HeyAlex** [comment]
there is a java sample in sample app
